// <auto-generated />
using FormulaOne.Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulaOne.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210194202_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormulaOne.Api.Entities.Database.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Circuits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sakhir",
                            Country = "Bahrain",
                            Lat = 26.032499999999999,
                            Lng = 50.510599999999997,
                            Name = "Bahrain International Circuit",
                            RoundNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Jeddah",
                            Country = "Saudi Arabia",
                            Lat = 21.631900000000002,
                            Lng = 39.104399999999998,
                            Name = "Jeddah Corniche Circuit",
                            RoundNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            City = "Melbourne",
                            Country = "Australia",
                            Lat = -37.849699999999999,
                            Lng = 144.96799999999999,
                            Name = "Albert Park Circuit",
                            RoundNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            City = "Suzuka",
                            Country = "Japan",
                            Lat = 34.8431,
                            Lng = 136.54069999999999,
                            Name = "Suzuka International Racing Course",
                            RoundNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            City = "Shanghai",
                            Country = "China",
                            Lat = 31.338899999999999,
                            Lng = 121.2197,
                            Name = "Shanghai International Circuit",
                            RoundNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            City = "Miami",
                            Country = "United States",
                            Lat = 25.958100000000002,
                            Lng = -80.238900000000001,
                            Name = "Miami International Autodrome",
                            RoundNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            City = "Imola",
                            Country = "Italy",
                            Lat = 44.343899999999998,
                            Lng = 11.716699999999999,
                            Name = "Autodromo Enzo e Dino Ferrari",
                            RoundNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            City = "Monte Carlo",
                            Country = "Monaco",
                            Lat = 43.734699999999997,
                            Lng = 7.4206000000000003,
                            Name = "Circuit de Monaco",
                            RoundNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            City = "Barcelona",
                            Country = "Spain",
                            Lat = 41.57,
                            Lng = 2.2610999999999999,
                            Name = "Circuit de Barcelona-Catalunya",
                            RoundNumber = 9
                        },
                        new
                        {
                            Id = 10,
                            City = "Montreal",
                            Country = "Canada",
                            Lat = 45.5,
                            Lng = -73.522800000000004,
                            Name = "Circuit Gilles Villeneuve",
                            RoundNumber = 10
                        },
                        new
                        {
                            Id = 11,
                            City = "Spielberg",
                            Country = "Austria",
                            Lat = 47.219700000000003,
                            Lng = 14.764699999999999,
                            Name = "Red Bull Ring",
                            RoundNumber = 11
                        },
                        new
                        {
                            Id = 12,
                            City = "Silverstone",
                            Country = "United Kingdom",
                            Lat = 52.078600000000002,
                            Lng = -1.0168999999999999,
                            Name = "Silverstone Circuit",
                            RoundNumber = 12
                        },
                        new
                        {
                            Id = 13,
                            City = "Budapest",
                            Country = "Hungary",
                            Lat = 47.578899999999997,
                            Lng = 19.2486,
                            Name = "Hungaroring",
                            RoundNumber = 13
                        },
                        new
                        {
                            Id = 14,
                            City = "Spa",
                            Country = "Belgium",
                            Lat = 50.437199999999997,
                            Lng = 5.9714,
                            Name = "Circuit de Spa-Francorchamps",
                            RoundNumber = 14
                        },
                        new
                        {
                            Id = 15,
                            City = "Zandvoort",
                            Country = "Netherlands",
                            Lat = 52.388800000000003,
                            Lng = 4.5408999999999997,
                            Name = "Circuit Zandvoort",
                            RoundNumber = 15
                        },
                        new
                        {
                            Id = 16,
                            City = "Monza",
                            Country = "Italy",
                            Lat = 45.615600000000001,
                            Lng = 9.2811000000000003,
                            Name = "Autodromo Nazionale Monza",
                            RoundNumber = 16
                        },
                        new
                        {
                            Id = 17,
                            City = "Baku",
                            Country = "Azerbaijan",
                            Lat = 40.372500000000002,
                            Lng = 49.853299999999997,
                            Name = "Baku City Circuit",
                            RoundNumber = 17
                        },
                        new
                        {
                            Id = 18,
                            City = "Singapore",
                            Country = "Singapore",
                            Lat = 1.2914000000000001,
                            Lng = 103.8639,
                            Name = "Marina Bay Street Circuit",
                            RoundNumber = 18
                        },
                        new
                        {
                            Id = 19,
                            City = "Austin",
                            Country = "United States",
                            Lat = 30.1328,
                            Lng = -97.641099999999994,
                            Name = "Circuit of the Americas",
                            RoundNumber = 19
                        },
                        new
                        {
                            Id = 20,
                            City = "Mexico City",
                            Country = "Mexico",
                            Lat = 19.404199999999999,
                            Lng = -99.090699999999998,
                            Name = "Autodromo Hermanos Rodriguez",
                            RoundNumber = 20
                        },
                        new
                        {
                            Id = 21,
                            City = "São Paulo",
                            Country = "Brazil",
                            Lat = -23.703600000000002,
                            Lng = -46.6997,
                            Name = "Autodromo Jose Carlos Pace",
                            RoundNumber = 21
                        },
                        new
                        {
                            Id = 22,
                            City = "Las Vegas",
                            Country = "United States",
                            Lat = 36.114699999999999,
                            Lng = -115.1728,
                            Name = "Las Vegas Street Circuit",
                            RoundNumber = 22
                        },
                        new
                        {
                            Id = 23,
                            City = "Lusail",
                            Country = "Qatar",
                            Lat = 25.489999999999998,
                            Lng = 51.4542,
                            Name = "Losail International Circuit",
                            RoundNumber = 23
                        },
                        new
                        {
                            Id = 24,
                            City = "Abu Dhabi",
                            Country = "UAE",
                            Lat = 24.467199999999998,
                            Lng = 54.603099999999998,
                            Name = "Yas Marina Circuit",
                            RoundNumber = 24
                        });
                });

            modelBuilder.Entity("FormulaOne.Api.Entities.Database.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Drivers", t =>
                        {
                            t.HasCheckConstraint("CK_Driver_Points", "Points >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Max Verstappen",
                            IsActive = true,
                            Nationality = "Dutch",
                            Number = 1,
                            Points = 437,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Sergio Perez",
                            IsActive = true,
                            Nationality = "Mexican",
                            Number = 11,
                            Points = 152,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Charles Leclerc",
                            IsActive = true,
                            Nationality = "Monegasque",
                            Number = 16,
                            Points = 356,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Carlos Sainz",
                            IsActive = true,
                            Nationality = "Spanish",
                            Number = 55,
                            Points = 290,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Lewis Hamilton",
                            IsActive = true,
                            Nationality = "British",
                            Number = 44,
                            Points = 234,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 6,
                            FullName = "George Russell",
                            IsActive = true,
                            Nationality = "British",
                            Number = 63,
                            Points = 217,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Lando Norris",
                            IsActive = true,
                            Nationality = "British",
                            Number = 4,
                            Points = 374,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Oscar Piastri",
                            IsActive = true,
                            Nationality = "Australian",
                            Number = 81,
                            Points = 292,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Fernando Alonso",
                            IsActive = true,
                            Nationality = "Spanish",
                            Number = 14,
                            Points = 70,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Lance Stroll",
                            IsActive = true,
                            Nationality = "Canadian",
                            Number = 18,
                            Points = 24,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Pierre Gasly",
                            IsActive = true,
                            Nationality = "French",
                            Number = 10,
                            Points = 42,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Esteban Ocon",
                            IsActive = true,
                            Nationality = "French",
                            Number = 31,
                            Points = 58,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 13,
                            FullName = "Alexander Albon",
                            IsActive = true,
                            Nationality = "Thai",
                            Number = 23,
                            Points = 12,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 14,
                            FullName = "Logan Sargeant",
                            IsActive = true,
                            Nationality = "American",
                            Number = 2,
                            Points = 6,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 15,
                            FullName = "Kevin Magnussen",
                            IsActive = true,
                            Nationality = "Danish",
                            Number = 20,
                            Points = 16,
                            TeamId = 8
                        },
                        new
                        {
                            Id = 16,
                            FullName = "Nico Hulkenberg",
                            IsActive = true,
                            Nationality = "German",
                            Number = 27,
                            Points = 31,
                            TeamId = 8
                        },
                        new
                        {
                            Id = 17,
                            FullName = "Daniel Ricciardo",
                            IsActive = true,
                            Nationality = "Australian",
                            Number = 3,
                            Points = 12,
                            TeamId = 9
                        },
                        new
                        {
                            Id = 18,
                            FullName = "Yuki Tsunoda",
                            IsActive = true,
                            Nationality = "Japanese",
                            Number = 22,
                            Points = 22,
                            TeamId = 9
                        },
                        new
                        {
                            Id = 19,
                            FullName = "Valtteri Bottas",
                            IsActive = true,
                            Nationality = "Finnish",
                            Number = 77,
                            Points = 0,
                            TeamId = 10
                        },
                        new
                        {
                            Id = 20,
                            FullName = "Zhou Guanyu",
                            IsActive = true,
                            Nationality = "Chinese",
                            Number = 24,
                            Points = 6,
                            TeamId = 10
                        });
                });

            modelBuilder.Entity("FormulaOne.Api.Entities.Database.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Milton Keynes",
                            Country = "Austria",
                            Name = "Red Bull Racing",
                            TeamPrincipal = "Christian Horner"
                        },
                        new
                        {
                            Id = 2,
                            City = "Maranello",
                            Country = "Italy",
                            Name = "Ferrari",
                            TeamPrincipal = "Frederic Vasseur"
                        },
                        new
                        {
                            Id = 3,
                            City = "Brackley",
                            Country = "Germany",
                            Name = "Mercedes",
                            TeamPrincipal = "Toto Wolff"
                        },
                        new
                        {
                            Id = 4,
                            City = "Woking",
                            Country = "United Kingdom",
                            Name = "McLaren",
                            TeamPrincipal = "Andrea Stella"
                        },
                        new
                        {
                            Id = 5,
                            City = "Silverstone",
                            Country = "United Kingdom",
                            Name = "Aston Martin",
                            TeamPrincipal = "Mike Krack"
                        },
                        new
                        {
                            Id = 6,
                            City = "Enstone",
                            Country = "France",
                            Name = "Alpine",
                            TeamPrincipal = "Oliver Oakes"
                        },
                        new
                        {
                            Id = 7,
                            City = "Grove",
                            Country = "United Kingdom",
                            Name = "Williams",
                            TeamPrincipal = "James Vowles"
                        },
                        new
                        {
                            Id = 8,
                            City = "Kannapolis",
                            Country = "United States",
                            Name = "Haas",
                            TeamPrincipal = "Ayao Komatsu"
                        },
                        new
                        {
                            Id = 9,
                            City = "Faenza",
                            Country = "Italy",
                            Name = "RB",
                            TeamPrincipal = "Laurent Mekies"
                        },
                        new
                        {
                            Id = 10,
                            City = "Hinwil",
                            Country = "Switzerland",
                            Name = "Kick Sauber",
                            TeamPrincipal = "Alessandro Alunni Bravi"
                        });
                });

            modelBuilder.Entity("FormulaOne.Api.Entities.Database.Driver", b =>
                {
                    b.HasOne("FormulaOne.Api.Entities.Database.Team", "Team")
                        .WithMany("Drivers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FormulaOne.Api.Entities.Database.Team", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
